### ISSUE TITLE
web app 和普通gweb 网页的区别

### ISSUE THREAD

**Issue by meflyup** [meflyup/eduapp#1]
- 请自由的在网络上找出web app和普通web网页型的网站各3项，并阐述为何你将这些网站划分为web app和普通网页。
- 阐述内容不少于800字。
> 提示，至少从这些维度阐述：
>  - 解决的问题;实现的理念
>  - 交互的设计
> - 信息的生成、组织、再造和传播 
- **提交时间：2017.9.29之前**
*待第三周学习协作开发工具链后提交*

**Comment by meflyup** [comment]
test

**Comment by Yuxiaoxue2015** [comment]
一、Web app实例包括webqq,web邮箱，wiki。
  由Web app的英文组成可以看出，web 意为电脑浏览器的网页，app 是指移动设备的一个应用软件，它们加起来就是一个能在电脑用的软件又能在移动设备端安装的软件，支持多平台运行。Web app是一种通过互联网访问的应用程序，是使用网页技术开发能够实现特定功能的APP。
相比普通web网页，Web app更侧重"功能"，每一个Web app都有自己特定的功能，解决用户特定的需求问题，用户可以根据个人需求来查找使用相应的app来实现一定的目标，简捷、方便、高效。比如，webqq为用户提供在线聊天、文件管理等服务，Web邮箱提供收发邮件服务，用户使用wiki可进行多人协作。并且Web app为用户提供了简洁的交互，交互设计往往考虑到用户的个性化需求，搜集最有效、准确的信息提供给用户，我们在使用时，可以问这样一个问题"这个程序是否完成了某个任务?"。即便它只完成了某个非常小的任务，那么它也是一个Web App。比如，Google的搜索引擎就是一个Web App，它本质上和电话查询服务没有什么区别。
Web qq可以作为一种为人类沟通交流服务的时时通讯工具，能满足人们文字聊天、发送语音、群聊等特定需求。web邮箱则可以为人们提供邮件发送与接收的服务，使人们跨越时间和空间的限制实现网上通讯。Wiki则是一种可供多人协同创作的站点，每个人都可以发表自己的意见或对共同的主题进行扩展或探讨，为协作协作提供必要的帮助，实现了快速广泛的信息整合。每个用户在使用过程中会生成并保存个人使用记录，当用户再次使用时，可查询删除或更新所有使用记录。
二、普通Web网页实例包括58同城，Blog,Food Scene。
  普通Web网页主要用途在于信息的呈现与发布，就像公告栏一样，人们可以浏览大量信息，常常用来做宣传、发布产品咨询、招聘等，为人们提供各个方面的咨询，但并不会根据用户的需求来主动提供个性化信息。信息发布在网页上，为用户提供丰富的资源库，被动地等待用户来点击浏览，而用户浏览网页的过程中，并不会是带着搜索某些特定信息的目的。普通Web网页与用户之间的交互性弱，二者属于主动浏览与被动点击的关系。
  58同城网与Blog类似，为用户提供了大量的招聘、咨询信息、生活信息服务，用户可在各分区点击浏览信息。而Food Scene公布的信息更加具体化，为用户呈现美食相关信息，通过精美的图片吸引用户的浏览欲望，并通过多种媒体手段来为用户展现信息。
